### ISSUE TITLE
Add ability to get euler angles

### ISSUE THREAD

**Issue by sjhansen3** [Achllle/dual_quaternions_ros#10]
For packages like:

https://github.com/ros-industrial-consortium/fermi/tree/hydro-devel/moveit_cartesian_plan_plugin

We sometimes need to convert between quaternions and euler angles. It owuld be nice to have a .euler property. Youd have to be explicit about the convention.

**Comment by Achllle** [comment]
To convert to Euler angles, I'd also have to convert translation. In that case, I'd probably also want to convert to several other conversions for rotation + translation which exist in other libraries. You can convert to quaternion + translation or to homogeneous representation and then to euler angles.
Also I'd rather discourage the use of RPY angles by explicitly not having them :)
